"use client";

import { useState, useEffect } from "react";
import { Wifi, Layers, Radio, ArrowRight } from "lucide-react";
import { Button } from "@/components/ui/button";
import GlassOverlay from "./GlassOverlay";

export default function WelcomeExplainer() {
  const [isOpen, setIsOpen] = useState(false);
  const [isMounted, setIsMounted] = useState(false);

  useEffect(() => {
    setIsMounted(true);
    const hasSeen = localStorage.getItem("mapee_explainer_seen");
    if (!hasSeen) {
      // Delay slightly for better UX so it doesn't pop up instantly before UI settles
      const timer = setTimeout(() => setIsOpen(true), 1200);
      return () => clearTimeout(timer);
    }
  }, []);

  const handleClose = () => {
    setIsOpen(false);
    localStorage.setItem("mapee_explainer_seen", "true");
  };

  // Prevent hydration styling mismatches
  if (!isMounted) return null;

  return (
    <GlassOverlay
      isOpen={isOpen}
      onClose={handleClose}
      title="Welcome to Mapee"
      className="max-w-md sm:max-w-md"
    >
      <div className="space-y-6 text-gray-300 antialiased font-sans">
        <p className="text-sm leading-relaxed text-muted-foreground">
          Mapee is a community-driven network mapping tool. Help us build a comprehensive map of global network quality!
        </p>
        
        <div className="space-y-5 pt-2">
          {/* Step 1 */}
          <div className="flex gap-4 items-start">
            <div className="w-10 h-10 rounded-full bg-neon-cyan/10 border border-neon-cyan/30 flex items-center justify-center shrink-0">
              <Wifi className="w-5 h-5 text-neon-cyan" />
            </div>
            <div>
              <h3 className="text-neon-cyan font-semibold text-sm mb-1 font-mono uppercase tracking-wider">1. Run a Network Test</h3>
              <p className="text-xs text-muted-foreground leading-relaxed">
                Click <span className="text-neon-green font-mono uppercase text-[10px] tracking-widest px-1 py-0.5 bg-neon-green/10 rounded">Initialize Scan</span> to capture your current network latency and signal quality.
              </p>
            </div>
          </div>

          {/* Step 2 */}
          <div className="flex gap-4 items-start">
            <div className="w-10 h-10 rounded-full bg-neon-green/10 border border-neon-green/30 flex items-center justify-center shrink-0">
              <Layers className="w-5 h-5 text-neon-green" />
            </div>
            <div>
              <h3 className="text-neon-cyan font-semibold text-sm mb-1 font-mono uppercase tracking-wider">2. Explore Data</h3>
              <p className="text-xs text-muted-foreground leading-relaxed">
                Use the Layers toggle on the map to view network performance heatmaps generated by community pings.
              </p>
            </div>
          </div>

          {/* Step 3 */}
          <div className="flex gap-4 items-start">
            <div className="w-10 h-10 rounded-full bg-neon-purple/10 border border-neon-purple/30 flex items-center justify-center shrink-0">
              <Radio className="w-5 h-5 text-neon-purple" />
            </div>
            <div>
              <h3 className="text-neon-cyan font-semibold text-sm mb-1 font-mono uppercase tracking-wider">3. Discover Cell Towers</h3>
              <p className="text-xs text-muted-foreground leading-relaxed">
                Toggle the Radio icon to reveal nearby cell towers and analyze local infrastructure coverage.
              </p>
            </div>
          </div>
        </div>

        <div className="pt-6 flex justify-end">
          <Button 
            onClick={handleClose}
            className="w-full sm:w-auto bg-neon-cyan/10 text-neon-cyan border border-neon-cyan hover:bg-neon-cyan hover:text-black font-mono font-bold tracking-widest group transition-all"
          >
            GET STARTED 
            <ArrowRight className="w-4 h-4 ml-2 group-hover:translate-x-1 transition-transform" />
          </Button>
        </div>
      </div>
    </GlassOverlay>
  );
}
